default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_backend_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_backend_test
  pool: 5
  username: postgres
  password: postgres

production:
  <<: *default
  database: hello_rails_backend_production
  username: postgres
  password: <%= ENV["HELLO_RAILS_FRONTEND_DATABASE_PASSWORD"] %>